### ISSUE TITLE
When promise are rejected the reason is not displayed

### ISSUE THREAD

**Issue by Bangsadrengur** [agirorn/jasmine-node-promise-matchers#11]
`expect(this.promisedAction()).toResolve(done)` 

displays `Failed: Promise was rejected` if the promise is rejected but not why where as 

`this.promisedAction.then(done).catch(done.fail)`

displays `Failed: reason for error from failed evaluation`.

Please update module so that reject reason is displayed.

**Comment by agirorn** [comment]
I'm not sure what you mean by the reason for the failed evaluation. Can you provide a compleat example where the matcher is not providing the info you want?

**Comment by Bangsadrengur** [comment]
index.js
```
module.exports = function () {
  return new Promise((resolve, reject) => {
    reject('This is the reason why');
  });
};
```

promise matcher test
```
var code = require('../');

describe('example', () => {
  beforeEach(function() {
    jasmine.addMatchers(require('jasmine-node-promise-matchers'));
  });

  it('should display behavior', done => {
    expect(code()).toResolve(done);
  });
});
```

output
```
Failures:
1) example should display behavior
  Message:
    Failed: Promise was rejected
  Stack:
```

without promise matchers
```
var code = require('../');

describe('example', () => {
  beforeEach(function() {
    jasmine.addMatchers(require('jasmine-node-promise-matchers'));
  });

  it('should display behavior', done => {
    code().then(done).catch(done.fail);
  });
});
```

output
```
Failures:
1) example should display behavior
  Message:
    Failed: This is the reason why
  Stack:
```

**Comment by agirorn** [comment]
The reason is not shown beaus you are not rejecting the promise with an error object. and you #13 is removing Nested error that is giving very good feedback when a promise is rejected with an error object. Baby what is missing is to handle the case when the error is not an actual error.

```
module.exports = function () {
  return new Promise((resolve, reject) => {
    reject(new Error('This is the reason why'));
  });
};
```

**Comment by Bangsadrengur** [comment]
Running the example as you showed it produced the following which is contains the information.
```
Failures:
1) example should display behavior
  Message:
    Failed: Promise was rejected
  Stack:
    NestedError: Promise was rejected
        at PATH/TO/node_modules/jasmine-node-promise-matchers/lib/promise-matchers.js:42:19
        at runMicrotasksCallback (node.js:327:7)
        at nextTickCallbackWith0Args (node.js:420:9)
        at process._tickCallback (node.js:349:13)
        at Function.Module.runMain (module.js:443:11)
        at startup (node.js:139:18)
        at node.js:974:3
    Caused By: Error: This is the reason why
        at PATH/TO/index.js:3:12
        at module.exports (PATH/TO/index.js:2:10)
        at Object.<anonymous> (PATH/TO/spec/index.spec.js:9:12)
```

This contains the proper error but I'm not convinced about the value of the added output.

The main error (the one in red in jasmine) becomes "Failed: Promise was rejected" so I have to search in the stack traces for the real reason. The "outer" stack trace is pointing me to the brake point in the promise matcher module ... something I don't need unless the promise matcher module is broken.

**Comment by Bangsadrengur** [comment]
It turns that the info is there after all. It's in the "caused by" part of the nested error.

I'm going to close this down and try it out a little bit better as is
