### ISSUE TITLE
Ugly errors when using `jasmine.any`

### ISSUE THREAD

**Issue by MiniGod** [agirorn/jasmine-node-promise-matchers#12]
When using jasmine.any, if a promise resolves with the wrong kind of value, the error message is not very nice.

Example:

`expect(promise).toResolveWith(jasmine.any(Number))`

Lets say `promise` resolves with a string `'123'` instead of the number `123`, then the following error is displayed:

`Failed: Expecting promise to be resolved with ("[object Object]") but was resolved with ("123")`

**Comment by agirorn** [comment]
In your mind what is the preferred output in this scenario ?

Do you know ho and if w can get better information jasmine.any matchers ?

**Comment by MiniGod** [comment]
When using the built in `.toHaveBeenCalledWith` matcher, which is the synchronous equivalent of `.toResolveWith` or `.toRejectWith`, the output is as follows:

    Expected spy callback to have been called with [ <jasmine.any(Number)> ] but actual calls were [ 'some string' ].

**Comment by agirorn** [comment]
Thanks for taking the time to report this. This is now fixed in version 0.1.2.
