### ISSUE TITLE
Feature: spy.and.resolveValue(value)?

### ISSUE THREAD

**Issue by MiniGod** [agirorn/jasmine-node-promise-matchers#14]
Maybe it doesn't belong here, but it would be great to be able to make a spy resolve with a value. It's sugar, but who doesn't like some sugar?

Currently have to do it like this:

```js
spyOn(module, 'method').and.returnValue(Promise.resolve('value'))
```

Suggestion:

```js
spyOn(module, 'method').and.resolveValue('value')
```

**Comment by agirorn** [comment]
You should push for this beeing part for jasmine core. It should be fairly simple she how returnValue is implemented [her](https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L4481).
