### ISSUE TITLE
Two different Errors are considered equal

### ISSUE THREAD

**Issue by MiniGod** [agirorn/jasmine-node-promise-matchers#15]
const a = new Error('a');
    const b = new Error('b');

    expect(Promise.reject(a)).toRejectWith(b, done);

passes although `a` and `b` are different.

The issue is that `deep-equal` consider them equal:
https://runkit.com/57e01e376dc2ad1400d39ab3/584826c627aa8e0013a1adcd

**Comment by agirorn** [comment]
Could be fixed when substack/node-deep-equal#48 gets merged.
