### ISSUE TITLE
Fail resolve matcher if promise is rejected and vice versa

### ISSUE THREAD

**Issue by MiniGod** [agirorn/jasmine-node-promise-matchers#5]
A promise can only be rejected or resolved once. Once it is resolved, it can not be rejected. Once it is rejected it can not be resolved.

With that in mind, a `.toReject` should fail as soon as the promise resolves. `.toResolve` should fail as soon as the promise rejects.

For example, if I write a test where I wait for the promise `.toRejectWith(jasmine.any(Error), done)`, it currently reaches a jasmine timeout. It should rather fail as soon as  the promise resolves.

**Comment by agirorn** [comment]
That has been working correctly from [first commit](https://github.com/agirorn/jasmine-node-promise-matchers/commit/40cd3b7f71a71fb2b88bc939a743990c85e4bc15#diff-94a5b9b89735b07e70940bc9556205baR122). Maybe the error message could bw adjusted to make it more clear what is braking **"Expecting promis to reject with 'value' but was resolved."**.
